version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  backend:
    build: ./backend
    command: uvicorn backend.app:app --host 0.0.0.0 --port 8001
    environment:
      DATABASE_URL: postgresql+psycopg2://app:app@db:5432/app
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./backend:/code
    depends_on:
      - db
      - redis
      - ollama
    ports:
      - "8001:8001"
  worker:
    build: ./backend
    command: celery -A backend.app.tasks worker -l info
    environment:
      DATABASE_URL: postgresql+psycopg2://app:app@db:5432/app
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./backend:/code
    depends_on:
      - db
      - redis
      - ollama
  beat:
    build: ./backend
    command: celery -A backend.app.tasks beat -l info
    environment:
      DATABASE_URL: postgresql+psycopg2://app:app@db:5432/app
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./backend:/code
    depends_on:
      - db
      - redis
      - ollama
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
  frontend:
    build: ./vue
    command: node server.js
    ports:
      - "8080:8080"
    volumes:
      - ./vue:/app
    depends_on:
      - backend
volumes:
  db-data:
